import React from 'react';

/**
 * Legal policy pages for ashvishevents.com, based on the company's official
 * policy documents (IT Act 2000 / Intermediaries Rules 2011 compliant).
 * Adapted for an event ticketing platform (returns/shipping clauses adapted
 * to "services" since tickets are digital event access).
 */

const UPDATED_DATE = '19 August 2026';
const SITE_URL = 'https://ashvishevents.com';

function PolicyShell({
  title,
  lastUpdated,
  children,
}: {
  title: string;
  lastUpdated?: string;
  children: React.ReactNode;
}) {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10">
      <div className="border-t-4 border-[#D4AF37] pt-6">
        <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight">{title}</h1>
        <p className="mt-2 text-sm text-gray-400">
          Last updated: {lastUpdated ?? UPDATED_DATE} · ashvishevents.com
        </p>
      </div>
      <article className="mt-8 text-gray-300 leading-relaxed space-y-5 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-white [&_h2]:mt-8 [&_h2]:mb-2 [&_h3]:text-lg [&_h3]:font-medium [&_h3]:text-[#D4AF37] [&_h3]:mt-6 [&_h3]:mb-2 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_li]:mb-2">
        {children}
      </article>
    </div>
  );
}

export function TermsPage() {
  return (
    <PolicyShell title="Terms & Conditions">
      <p>
        This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules thereunder as applicable and the amended
        provisions pertaining to electronic records in various statutes as
        amended by the Information Technology Act, 2000. This electronic record
        is generated by a computer system and does not require any physical or
        digital signatures.
      </p>
      <p>
        This document is published in accordance with the provisions of Rule
        3(1) of the Information Technology (Intermediaries Guidelines) Rules,
        2011, which require the publication of the rules and regulations,
        privacy policy and Terms of Use for access or usage of the domain name{' '}
        <a href={SITE_URL} className="text-[#D4AF37] underline">
          {SITE_URL}
        </a>{' '}
        ("Website"), including the related mobile site and mobile application
        (hereinafter referred to as the "Platform").
      </p>
      <p>
        The Platform is owned and operated by <strong>Ash Vish Events</strong>{' '}
        with its registered office at Laxmi Road, Kolhapur, Maharashtra, India
        (hereinafter referred to as "Platform Owner", "we", "us", "our").
      </p>
      <h2>Your Agreement with Us</h2>
      <p>
        Your use of the Platform and its services and tools is governed by the
        following Terms of Use ("Terms of Use") as applicable to the Platform,
        including the applicable policies incorporated herein by reference. If
        you transact on the Platform, you shall be subject to the policies that
        are applicable to the Platform for such transaction. By mere use of the
        Platform, you shall be contracting with the Platform Owner, and these
        terms and conditions, including the policies, constitute your binding
        obligations to the Platform Owner. These Terms of Use relate to your use
        of our website and services (collectively, "Services"). Any terms and
        conditions proposed by you which are in addition to or which conflict
        with these Terms of Use are expressly rejected by the Platform Owner and
        shall be of no force or effect. These Terms of Use may be modified at
        any time without assigning any reason. It is your responsibility to
        periodically review these Terms of Use to stay informed of updates.
      </p>
      <p>
        For the purposes of these Terms of Use, wherever the context so
        requires, "you", "your" or "user" shall mean any natural or legal
        person who has agreed to become a user/buyer on the Platform.
      </p>
      <p className="font-semibold text-white">
        ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
        AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO
        PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
      </p>
      <h2>Terms of Use of the Platform</h2>
      <p>
        The use of the Platform and/or availing of our Services is subject to
        the following terms of use:
      </p>
      <ul>
        <li>
          To access and use the Services, you agree to provide true, accurate
          and complete information to us during and after registration, and you
          shall be responsible for all acts done through the use of your
          registered account on the Platform.
        </li>
        <li>
          Neither we nor any third parties provide any warranty or guarantee as
          to the accuracy, timeliness, performance, completeness or suitability
          of the information and materials offered on this website or through
          the Services, for any specific purpose. You acknowledge that such
          information and materials may contain inaccuracies or errors, and we
          expressly exclude liability for any such inaccuracies or errors to the
          fullest extent permitted by law.
        </li>
        <li>
          Your use of our Services and the Platform is solely and entirely at
          your own risk and discretion, for which we shall not be liable to you
          in any manner. You are required to independently verify the details of
          any event (including date, time, venue and artist lineup) before
          purchasing a ticket.
        </li>
        <li>
          You shall be responsible for your own conduct while using the Platform
          and for any consequences thereof. You shall comply with all applicable
          local laws while using the Platform.
        </li>
        <li>
          You acknowledge and agree that we own all proprietary rights to the
          Platform and the Services, including all designs, text, graphics,
          logos, icons, images, audio clips, video clips, digital downloads and
          compilations of data. No right or licence is granted to you in respect
          of any of these.
        </li>
        <li>
          You agree to pay us the charges associated with availing the Services.
        </li>
        <li>
          You agree not to use the Platform and/or Services for any purpose that
          is unlawful, illegal or forbidden by these Terms, or by Indian or
          local laws that might apply to you. This includes, without limitation,
          any unauthorised resale, transfer, or commercial use of tickets
          purchased on the Platform.
        </li>
        <li>
          You agree and acknowledge that the Website and the Services may
          contain links to other third-party websites. On accessing these links,
          you will be governed by the terms of use, privacy policy and such
          other policies of such third-party websites. These links are provided
          for your convenience and to provide further information.
        </li>
        <li>
          You understand that upon initiating a transaction for availing the
          Services, you are entering into a legally binding and enforceable
          contract with the Platform Owner for the Services.
        </li>
        <li>
          You shall indemnify and hold harmless the Platform Owner, its
          affiliates, group companies (as applicable) and their respective
          officers, directors, agents, and employees, from any claim or demand,
          or actions including reasonable attorney's fees, made by any third
          party or penalty imposed due to or arising out of your breach of these
          Terms of Use, the Privacy Policy and other policies, or your violation
          of any law, rules or regulations or the rights (including
          infringement of intellectual property rights) of a third party.
        </li>
        <li>
          Notwithstanding anything contained in these Terms of Use, the parties
          shall not be liable for any failure to perform an obligation under
          these Terms if performance is prevented or delayed by a force majeure
          event.
        </li>
        <li>
          These Terms and any dispute or claim relating to it, or its
          enforceability, shall be governed by and construed in accordance with
          the laws of India.
        </li>
        <li>
          All disputes arising out of or in connection with these Terms shall be
          subject to the exclusive jurisdiction of the courts in Kolhapur,
          Maharashtra, India.
        </li>
        <li>
          All concerns or communications relating to these Terms must be
          communicated to us using the contact information provided on this
          website.
        </li>
      </ul>
      <h2>Tickets Are Personal and Non-Transferable</h2>
      <p>
        A digital ticket / QR pass purchased on the Platform is issued for the
        named attendee and is intended to be used only by that person, subject
        to the check-in process at the venue. You agree not to share, resell,
        transfer or otherwise distribute tickets purchased on the Platform
        except as expressly permitted by the Platform Owner.
      </p>
    </PolicyShell>
  );
}

export function RefundPolicyPage() {
  return (
    <PolicyShell title="Refund & Cancellation Policy">
      <p>
        This Refund and Cancellation Policy outlines how you can cancel or seek
        a refund for a product / service that you have purchased through the
        Platform. Under this policy:
      </p>
      <ol>
        <li>
          <strong>Cancellation window:</strong> Cancellations will only be
          considered if the request is made within 1 (one) day of placing the
          order. However, cancellation requests may not be entertained if the
          event has been confirmed with the venue/organiser and tickets have
          been issued, or if the event is already underway. In such cases,
          please raise the matter with our customer support team.
        </li>
        <li>
          <strong>Perishable / consumable services:</strong> Ash Vish Events
          does not accept cancellation requests for perishable items like
          flowers, eatables, etc. However, a refund / replacement can be made if
          the user establishes that the quality of the product delivered is not
          good.
        </li>
        <li>
          <strong>Damaged or defective deliverables:</strong> In case of receipt
          of damaged or defective items (where applicable), please report to our
          customer service team. The request would be entertained once Ash Vish
          Events has checked and determined the issue at its own end. This
          should be reported within 1 (one) day of receipt of the
          product/service. In case you feel that the product received is not as
          shown on the site or as per your expectations, you must bring it to
          the notice of our customer service within 1 (one) day. The customer
          service team, after looking into your complaint, will take an
          appropriate decision.
        </li>
        <li>
          <strong>Event cancellation or postponement:</strong> In case an event
          is cancelled or postponed by the organiser or the venue, tickets
          purchased through the Platform will be refunded in full to the
          original mode of payment. No refund will be granted for change of
          mind once tickets have been issued, unless mandated by applicable
          law.
        </li>
        <li>
          <strong>Warranted products:</strong> In case of complaints regarding
          products that come with a warranty from the manufacturers, please
          refer the issue to the manufacturers.
        </li>
        <li>
          <strong>Refund processing time:</strong> In case of any refund
          approved by Ash Vish Events, it will take up to 7 (seven) days for the
          refund to be processed to you, in addition to the timelines followed
          by your bank / payment gateway.
        </li>
      </ol>
      <h2>Return Policy</h2>
      <p>
        Where Ash Vish Events sells physical merchandise or deliverable items
        through the Platform, we offer refund / exchange within the first 1
        (one) day from the date of your purchase. If 1 (one) day has passed
        since your purchase, you will not be offered a return, exchange or
        refund of any kind. In order to become eligible for a return or an
        exchange, (i) the purchased item should be unused and in the same
        condition as you received it, (ii) the item must have its original
        packaging, and (iii) if the item was purchased on a sale, it may not be
        eligible for a return / exchange. Further, only such items are replaced
        by us (based on an exchange request) if such items are found to be
        defective or damaged.
      </p>
      <p>
        You agree that there may be certain categories of products / items that
        are exempted from returns or refunds. Such categories of products would
        be identified to you at the time of purchase. For exchange / return
        accepted request(s) (as applicable), once your returned product / item
        is received and inspected by us, we will send you an email to notify you
        about receipt of the returned / exchanged product. If the item is
        approved after quality check at our end, your request (i.e. return /
        exchange) will be processed in accordance with our policies.
      </p>
      <h2>Shipping Policy</h2>
      <p>
        Orders for the user are shipped through registered domestic courier
        companies and/or speed post only, where physical delivery is
        applicable. Orders are shipped within 7 (seven) days from the date of
        the order and/or payment, or as per the delivery date agreed at the time
        of order confirmation, subject to courier company / post office norms.
        The Platform Owner shall not be liable for any delay in delivery by the
        courier company / postal authority. Delivery of all orders will be made
        to the address provided by the buyer at the time of purchase. Delivery
        of our digital services (tickets) will be confirmed on your email ID and
        WhatsApp number as specified at the time of booking. If there are any
        shipping cost(s) levied by the seller or the Platform Owner (as the case
        may be), the same is not refundable.
      </p>
      <h2>Contact Us</h2>
      <p>
        For any refund or cancellation requests, please write to us using the
        contact details provided on the Website, or reach our support team
        Monday – Friday, 9:00 – 18:00.
      </p>
    </PolicyShell>
  );
}

export function PrivacyPolicyPage() {
  return (
    <PolicyShell title="Privacy Policy">
      <h2>Introduction</h2>
      <p>
        This Privacy Policy describes how Ash Vish Events and its affiliates
        (collectively "Ash Vish Events", "we", "our", "us") collect, use, share,
        protect or otherwise process your information / personal data through
        our website{' '}
        <a href={SITE_URL} className="text-[#D4AF37] underline">
          {SITE_URL}
        </a>{' '}
        (hereinafter referred to as the "Platform"). Please note that you may be
        able to browse certain sections of the Platform without registering with
        us. We do not offer any product/service under this Platform outside
        India and your personal data will primarily be stored and processed in
        India. By visiting this Platform, providing your information or availing
        any product/service offered on the Platform, you expressly agree to be
        bound by the terms and conditions of this Privacy Policy, the Terms of
        Use and the applicable service/product terms and conditions, and agree
        to be governed by the laws of India including, but not limited to, the
        laws applicable to data protection and privacy. If you do not agree,
        please do not use or access our Platform.
      </p>
      <h2>Collection of Personal Data</h2>
      <p>
        We collect your personal data when you use our Platform, services or
        otherwise interact with us during the course of our relationship, and
        related information provided from time to time. Some of the information
        that we may collect includes, but is not limited to, personal data /
        information provided to us during sign-up/registering or while using our
        Platform such as name, date of birth, address, telephone/mobile number,
        email ID and/or any such information shared as proof of identity or
        address. Some sensitive personal data may be collected with your
        consent, such as your bank account or credit/debit card or other payment
        instrument information (in order to enable ticket purchases on the
        Platform), all of the above being in accordance with applicable
        laws. You always have the option to not provide information, by choosing
        not to use a particular service or feature on the Platform.
      </p>
      <p>
        We may track your behaviour, preferences, and other information that you
        choose to provide on our Platform. This information is compiled and
        analysed on an aggregated basis. We will also collect your information
        related to your transactions on the Platform and such third-party
        business partner platforms. When such a third-party business partner
        collects your personal data directly from you, you will be governed by
        their privacy policies. We shall not be responsible for the
        third-party business partner's privacy practices.
      </p>
      <h2>How We Use Your Information</h2>
      <ul>
        <li>
          To issue, deliver and verify digital tickets, including sending your
          digital QR pass to your email and WhatsApp number.
        </li>
        <li>To process payments through our authorised payment gateways.</li>
        <li>
          To communicate with you about your bookings, event updates,
          cancellations and important announcements.
        </li>
        <li>To improve our Platform, services and customer experience.</li>
        <li>To comply with applicable legal and regulatory obligations.</li>
      </ul>
      <h2>Storage and Protection of Data</h2>
      <p>
        We take your privacy seriously and take all reasonable precautions to
        protect your personal data in our possession or whenever you access your
        account information. We adhere to our security guidelines to protect it
        against unauthorised access and offer the use of a secure server.
        However, the transmission of information is not completely secure for
        reasons beyond our control. By using the Platform, the users accept the
        security implications of data transmission over the internet and the
        World Wide Web, which cannot always be guaranteed as completely secure,
        and therefore there would always remain certain inherent risks regarding
        use of the Platform. Users are responsible for ensuring the protection
        of login and password records for their account.
      </p>
      <h2>Data Deletion and Retention</h2>
      <p>
        You have an option to delete your account by visiting your profile and
        settings on our Platform; this action would result in you losing all
        information related to your account. You may also write to us at the
        contact information provided below to assist you with these requests.
        We may, in the event of any pending grievance, claims, pending shipments
        or any other services, refuse or delay deletion of the account. Once the
        account is deleted, you will lose access to the account. We retain your
        personal data for a period no longer than is required for the purpose
        for which it was collected or as required under any applicable law.
        However, we may retain data related to you if we believe it may be
        necessary to prevent fraud or future abuse or for other legitimate
        purposes. We may continue to retain your data in anonymised form for
        analytical and research purposes.
      </p>
      <h2>Your Rights</h2>
      <p>
        You may access, rectify, and update your personal data directly through
        the functionalities provided on the Platform.
      </p>
      <h2>Consent</h2>
      <p>
        By visiting our Platform or by providing your information, you consent
        to the collection, use, storage, disclosure and otherwise processing of
        your information on the Platform in accordance with this Privacy Policy.
        If you disclose to us any personal data relating to other people, you
        represent that you have the authority to do so and permit us to use the
        information in accordance with this Privacy Policy. While providing your
        personal data over the Platform or any partner platforms or
        establishments, you consent to us (including our other corporate
        entities, affiliates, lending partners, technology partners, marketing
        channels, business partners and other third parties) contacting you
        through SMS, instant messaging apps (including WhatsApp), call and/or
        e-mail for the purposes specified in this Privacy Policy.
      </p>
      <p>
        You have an option to withdraw your consent that you have already
        provided by writing to the Grievance Officer at the contact information
        provided below. Please mention "Withdrawal of consent for processing
        personal data" in the subject line of your communication. We may verify
        such requests before acting on them. Please note that your withdrawal of
        consent will not be retrospective and will be in accordance with the
        Terms of Use, this Privacy Policy, and applicable laws. In the event you
        withdraw consent given to us under this Privacy Policy, we reserve the
        right to restrict or deny the provision of our services for which we
        consider such information to be necessary.
      </p>
      <h2>Changes to this Privacy Policy</h2>
      <p>
        Please check our Privacy Policy periodically for changes. We may update
        this Privacy Policy to reflect changes to our information practices. We
        may alert / notify you about significant changes to the Privacy Policy,
        in the manner as may be required under applicable laws.
      </p>
      <h2>Grievance Officer</h2>
      <p>
        In accordance with the Information Technology Act, 2000 and rules made
        thereunder, the name and contact details of the Grievance Officer are
        provided below:
      </p>
      <p>
        <strong>Name:</strong> Ash Vish Events (Support Team)
        <br />
        <strong>Designation:</strong> Grievance Officer
        <br />
        <strong>Address:</strong> Laxmi Road, Kolhapur, Maharashtra, India
        <br />
        <strong>Phone:</strong> +91 96573 33033 (Monday – Friday, 9:00 – 18:00)
        <br />
        <strong>Email:</strong> support@ashvishevents.com
      </p>
    </PolicyShell>
  );
}
